### ISSUE TITLE
Immunity to SMA not responding

### ISSUE THREAD

**Issue by caand** [derenback/Domoticz-SMA-Inverter#15] opened 2022-08-15 10:35 UTC
Hi,
The plugin has trouble to cope with a missing inverter - for example, wrong IP or port:
1. Variable "client" becomes undefined in two places, so I moved it inside "try":
------
    try:
        global client
        client = ModbusClient(host=Parameters["Address"], port=Parameters["Port"], unit_id=Parameters["Mode1"])
        client.open()
        Domoticz.Log("SMA Inverter serial number: " + str(get_modbus_value(SERIAL_NUMBER_ADDRESS)))
    except:
        Domoticz.Log("SMA Inverter connection problem")
------
def onHeartbeat():
    try:
        if not client.is_open():
            Domoticz.Log("SMA inverter not connected. Reconnecting...")
            client.open()
    except:
        Domoticz.Log("SMA Inverter connection problem");
        return
------
2. I'm getting in log:
2022-08-15 12:20:00.313 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 6, sValue: '', sUsage: '0', dType: 113, sType: 0)
2022-08-15 12:20:16.207 Error: WebServer PO exception occurred : 'stoull' 
which confuses the web server, making all utilities an devices dissapear (they come back after deleting the SMA hardware). I don't know how to fix it.

Thanks, Calin

**Comment by derenback** [comment] 2022-08-15 17:26
Have you tried the latest version of the plugin? (0.9.4) or what version did you use?

**Comment by caand** [comment] 2022-08-15 18:32
Hi,
I had version 092. Now, with 094, issue 1 above is solved, but issue 2 is still present, apparently every five minutes. On top, I see some initial errors in the log (Solar is the name of the SMA hardware):

2022-08-15 20:20:11.197 Error: Solar: PyDomoticz_Log failed to parse parameters: string expected.
2022-08-15 20:20:11.197 Error: Solar: 'PyDomoticz_Log' failed 'TypeError'.
2022-08-15 20:20:11.197 Error: Solar: 'onStart' failed 'SystemError':'<built-in function Log> returned a result with an error set'.
2022-08-15 20:20:11.197 Error: Solar: Exception traceback:
2022-08-15 20:20:11.197 Error: Solar: ----> Line 131 in '/home/pi/domoticz/plugins/Domoticz-SMA-Inverter/plugin.py', function onStart
2022-08-15 20:25:00.331 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 6, sValue: '', sUsage: '0', dType: 113, sType: 0)
2022-08-15 20:25:10.944 Error: WebServer PO exception occurred : 'stoull'
2022-08-15 20:30:00.545 Error: UpdateMeter: Error converting sValue/sUsage! (IDX: 6, sValue: '', sUsage: '0', dType: 113, sType: 0)
2022-08-15 20:30:48.127 Error: WebServer PO exception occurred : 'stoull' 

Short explanation: I expect to have the inverter installed in the next days, and I just tried the plugin to see the devices and options. I hope these troubles are only happening when the inverter is not present at the "add hardware" moment, and not if the connection fails later...

**Comment by derenback** [comment] 2022-08-15 18:56
I guess the problem here is that you have never had a working connection. I have tried to reproduce the issue on a new instance of domoticz running in docker but I do not get the same problem. I do get errors due to not connecting when setting the IP to a different address but all the devices are created and does not vanish... I hope it will work better as soon as you get your inverter. 

As soon as I set the IP correct it does connect and is working as it should. 

Please let me know if the issue persist when you have your inverter installed.

**Comment by caand** [comment] 2022-08-23 14:46
Got the inverter, everything works very well.

Thanks for all the work!

**Comment by derenback** [comment] 2022-08-23 15:18
Great! Thancks for the feedback. I'll close this issue now.

**Closed as completed by derenback** 2022-08-23 15:18 UTC
